apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.selectorLabel }}-load-balancer
  name: {{ .Values.fullName}}-load-balancer
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.p2p }}
      name: p2p
  selector:
    app: {{ .Values.selectorLabel }}



